config/routes.rb
Rails.application.routes.draw do
  
  resources :faculties
  get 'faculties/new'
  post 'faculties/new'

  get 'welcome/index'
  root 'welcome#index'
  get "inicio", to: "welcome#index"

   

end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:cod, :name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/faculties/_form.html.erb
<%= form_for(@faculty) do |f| %>
  <% if @faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
      <% @faculty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cod %><br>
    <%= f.number_field :cod %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn black'%>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1 class="center-align">Editar facultad</h1>

<div class="row">
    <div class="col l6 offset-l3 m8 offset-m2 s10 offset-s1">
        <div class="card-panel white">
			<%= render 'form'%>
			<%= link_to 'Mostrar', @faculty %> |
			<%= link_to 'Volver', faculties_path %>
        </div>
    </div>
</div>

app/views/faculties/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
    <div class="row">
        <div class="col s12"> 
          <h1>Facultades 
          <a href="faculties/new" class="waves-effect waves-light btn-floating btn-large green darken-1">+</a>
          </h1>
          <table class="striped centered responsive-table">
            <thead>
              <tr>
                <th>Cod</th>
                <th>Nombre</th>
                <th colspan="3">Opciones</th>
              </tr>
            </thead>
            <tbody>
              <% @faculties.each do |faculty| %>
                <tr>
                  <td><%= faculty.cod %></td>
                  <td><%= faculty.name %></td>
                  <td><%= link_to 'Mostrar', faculty ,class: 'btn black'%></td>
                  <td><%= link_to 'Editar', edit_faculty_path(faculty) ,class: 'btn black'%></td>
                  <td><%= button_to 'Eliminar', faculty, :method => :delete,class: 'btn red'%></td>
                </tr>
              <% end %>
            </tbody>
          </table>
       </div>
    </div>
</div>

app/views/faculties/new.html.erb
<h1 class="center-align">Nueva facultad</h1>

<div class="row">
    <div class="col l6 offset-l3 m8 offset-m2 s10 offset-s1">
        <div class="card-panel white">
			<%= render 'form'%>
			<%= link_to 'Volver', faculties_path %>
        </div>
    </div>
</div>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col l6 offset-l3 m8 offset-m2 s10 offset-s1">
    <div class="card white">
      <div class="card-content black-text">
        <span class="card-title black-text">Facultad</span>
          <p>
        		<strong>Cod:</strong>
        		<%= @faculty.cod %>
				  </p>
				  <p>
        		<strong>Name:</strong>
        		<%= @faculty.name %>
				  </p>
      </div>
      <div class="card-action">
        <%= link_to 'Editar', edit_faculty_path(@faculty) %> |
				<%= link_to 'Volver', faculties_path %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Pronto...</title>
		<%= stylesheet_link_tag 'materialize', media: 'all', 'data-turbolinks-track' => true %>
	</head>

	<body class='orange'>
		<%= yield %>
		<%= javascript_include_tag 'jquery-1.10.2'%>
		<%= javascript_include_tag 'materialize.min'%>
	</body>
</html>

app/views/welcome/index.html.erb
<h1 class="center-align blue-grey-text text-darken-4"><b>¡Bienvenid@!</b></h1>
<br>
<p class="center-align blue-grey-text text-darken-4"><b>Pronto una nueva web para ti ;)</b></p>

<div class="center-align">
	<%= image_tag("rss.jpg", :alt => "rss feed")%>
</div>


<!--
<div class="container">
    <div class="row">
        <div class="col l6 offset-l3 m8 offset-m2 s10 offset-s1">
	        <div class="card-panel blue-grey lighten-5">
			    <form >
			      <div class="row">
			        <div class="input-field col s12 center-align">
			          <input id="email" type="email" class="validate">
			          <label for="email">Correo</label>
			        </div>
			      </div>
			 
			      <div class="row">
			        <div class="input-field col s12 center-align">
			          <input id="password" type="password" class="validate">
			          <label for="password">Contraseña</label>
			        </div>
			      </div>
			      <a class="left-align waves-effect waves-light btn blue-grey darken-4">Entrar</a>
			    </form>
	        </div>
        </div>
    </div>
</div>
-->